### ISSUE TITLE
Module "npm-angular5-provider$core-js@2.5.7/modules/_is-object" has not been loaded yet for context

### ISSUE THREAD

**Issue by wsyski** [izaera/liferay-npm-bundler-2-example#1]
I have tried this example with Liferay 7 GA7 and got the following error:
<pre>
Uncaught (in promise) Error: Module "npm-angular5-provider$core-js@2.5.7/modules/_is-object" has not been loaded yet for context: npm-angular5-provider$core-js@2.5.7/modules/_bind
    at loader.js?browserId=other&minifierType=&languageId=en_US&b=7006&t=1531747242268:3179
    at Function.<anonymous> (_bind.js:3)
    at Loader._setModuleImplementation (loader.js?browserId=other&minifierType=&languageId=en_US&b=7006&t=1531747242268:3136)
    at Function.defineModules (loader.js?browserId=other&minifierType=&languageId=en_US&b=7006&t=1531747242268:3250)
    at loader.js?browserId=other&minifierType=&languageId=en_US&b=7006&t=1531747242268:2533
</pre>

The same error with the latest version of npm bundler v2.1.1
The example works fine in the Liferay 7.1.x branch

The problem seems to be visible at:
http://localhost:6080/o/js_loader_modules

"npm-angular5-provider$core-js@2.5.7/modules/_bind": {
  "dependencies": [],
  "map": {}
},

Dependencies are missing there. They are fine for example for _to_primitive:
"npm-angular5-provider$core-js@2.5.7/library/modules/_to-primitive": {
  "dependencies": ["module", "exports", "require", "./_is-object"],
  "map": {}
},

Is it possible to fix this in the 7.0.x branch?

**Comment by izaera** [comment]
As explained [here](https://community.liferay.com/blogs/-/blogs/why-we-need-a-new-liferay-npm-bundler-3-of-3-?_com_liferay_blogs_web_portlet_BlogsPortlet_redirect=https%3A%2F%2Fcommunity.liferay.com%3A443%2Fblogs%3Fp_p_id%3Dcom_liferay_blogs_web_portlet_BlogsPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_com_liferay_blogs_web_portlet_BlogsPortlet_cur%3D2%26_com_liferay_blogs_web_portlet_BlogsPortlet_delta%3D10%26p_r_p_resetCur%3Dfalse):

``` 
this example is supposed to be run in Liferay 7.1.0 B2 at least (download it from here). It will not work in Liferay 7.0.0 unless you do some modifications!
```

Even if you do the necessary modifications to the dependencies in the build.gradle files, you can still be hit by bugs that have not been backported to 7.0.0 by the time this example was done (I think that includes at least an LPS related to what you are experiencing). If you have a DXP subscription you can ask support for fixes to that bugs, I believe.

However, it's not the intention of this project to be maintained, just to serve as example of the blog entry. Please look at blade templates or samples for fully supported examples.

Thanks.
